version: "3.8"
services:
  temp-database:
    image: ghcr.io/jyss44/temperature-database:latest
    volumes:
      - ${PWD}/database:/app/database
    command: -port ${DATABASE_PORT} -dbpath database/${DB_FILE}
    ports:
      - ${DATABASE_PORT}:8080

  temp-monitor:
    image: ghcr.io/jyss44/temperature-monitor:latest
    depends_on:
      - temp-database
    privileged: true
    command: -port ${MONITOR_PORT} -dburl http://temp-database:${DATABASE_PORT}
    ports:
      - ${MONITOR_PORT}:6969

  graph:
    image: ghcr.io/jyss44/temperature-graph-py
    depends_on:
      - temp-database
      - temp-monitor
    command: -p ${GRAPH_PORT} -db http://temp-database:${DATABASE_PORT} -t http://temp-monitor:${MONITOR_PORT}
    ports:
      - ${GRAPH_PORT}:8888