version: "3.8"
services:
  temp-database:
    image: ghcr.io/jyss44/temperature-database:latest
    volumes:
      - ${PWD}/database:/app/database
    command: -port ${DATABASE_PORT} -dbpath database/${DB_FILE}
    ports:
      - ${DATABASE_PORT}:8080

  temp-monitor:
    image: ghcr.io/jyss44/temperature-monitor:latest
    depends_on:
      - temp-database
    privileged: true
    command: -port ${MONITOR_PORT} -dburl http://temp-database:${DATABASE_PORT}
    ports:
      - 6969:6969