version: "3.8"
services:
  temp-database:
    image: ghcr.io/jyss44/temperature-monitor:latest
    volumes:
      - ${PWD}/database:/app/database
    command: -port ${DATABASE_PORT} -dbpath database/${DB_FILE}

  temp-monitor:
    image: ghcr.io/jyss44/temperature-monitor:latest
    depends_on:
      - temp-database
    privileged: true
    command: -port ${MONITOR_PORT} -databaseurl http://temp-database:${DATABASE_PORT}